### ISSUE TITLE
Not obvious that phone is required

### ISSUE THREAD

**Issue by richardolsson** [zetkin/call.zetk.in#64]
It is not directly obvious to test subjects that they need to user their own phone to dial. Even subjects who have previously taken part in phone banking using legacy Zetkin have to stop to think before realizing that they need to dial the number themselves. They are not sure whether the tool is capable of dialling on it's own (using VoIP).

_This was observed (noted as signal 4) during the december 2016 user tests._

**Comment by jensborje** [comment]
Posible solutions:
- Have a friendly introduction to what caller need at hand in order to call (phone to call with, paper and pen to take notes during call, etc). This could be placed on assignment pane when entering the call session.
- Getter guidance when first enter call step. Perhaps a obtrusive tooltip stating that it is time to pick up their phone and dial the number, which could be pointed out on the screen.

**Comment by richardolsson** [comment]
@jensborje to create a mock-up of what this might look like, consistent with `LaneSwitch` tooltip as discussed in #77.
